numerator =100, denominator = 'a'

try{
    console.log(numerator/denominator)

    console.log(a)
}
catch(error){
    console.log("An error occured")
    console.log('error message: '+error)
}
finally{
    console.log("This statement will be always executed :)");
}